[package]
name = "gib"
version = "0.5.0"
description = "A Game Boy emulator written in Rust"
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"

[workspace]
members = ["gib-core"]

[dependencies]
gib-core = { path = "gib-core" }
glium = { version = "0.22", default-features = true }
glutin = "0.18"
imgui = "0.0.21"
imgui-sys = "0.0.21"
imgui-glium-renderer = "0.0.21"
failure = "0.1.5"
clap = "2.32.0"
cpal = "0.8.2"

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false

[profile.release]
debug = true
