[package]
name = "gb-rs"
version = "0.1.0"
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"

[dependencies]
glium = { version = "0.22", default-features = true }
glutin = "0.18"
imgui = "0.0.21"
imgui-sys = "0.0.21"
imgui-glium-renderer = "0.0.21"

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false

[profile.release]
debug = true
