[package]
name = "gib"
version = "0.5.0"
description = "A Game Boy emulator written in Rust"
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"

[workspace]
members = ["gib-core"]

[dependencies]
gib-core = { path = "gib-core" }
gfx = "0.17"
gfx_core = "0.8.3"
gfx_device_gl = "0.15.5"
gfx_window_glutin = "0.28"
glutin = "0.19"
imgui = "0.0.22"
imgui-sys = "0.0.22"
imgui-gfx-renderer = "0.0.22"
imgui-winit-support = "0.0.22"
failure = "0.1.5"
clap = "2.32.0"
cpal = "0.8.2"

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false

[profile.release]
debug = true
