[package]
name = "gb-rs"
version = "0.1.0"
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.32"

[profile.dev]
overflow-checks = false

[profile.release]
debug = true