version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Install devtools
          command: |
            sudo apt update
            sudo apt install libasound2-dev

            rustup install nightly
      - run:
          name: Version information
          command: |
            rustc +nightly --version --verbose
            cargo +nightly --version --verbose
      - run:
          name: Build
          command: cargo +nightly build --release
      - run:
          name: Run tests
          command: cargo +nightly test --release --all